### ISSUE TITLE
Creating generic exchange methods for session objects

### ISSUE THREAD

**Issue by bustoutfunk** [adamhyman/dinar-trader#4]
Create generalized methods to query, buy, sell, trade, etc. in the exchange_session class.

**Comment by bustoutfunk** [comment]
@adamhyman, I have created a [generalized class](https://github.com/adamhyman/dinar-trader/blob/master/exchange_session.py) that will encompass a session from any of the exchanges (just Kraken and Gemini for now).

You won't notice any difference as of right now but this issue requests an enhancement to create an "all encompassing API." I plan to create generic methods that will enable us to buy, sell, trade, etc. without going into the specific exchange API methods.

**Comment by adamhyman** [comment]
This is really awesome.  I understand what that code is doing and will be able to add on other exchanges in a similar fashion.

My question:  In [exchange_session.py](https://github.com/adamhyman/dinar-trader/blob/master/exchange_session.py) we have "import krakenex" - but how does it know that krakenex is located inside python3-krakenex?

**Comment by bustoutfunk** [comment]
Good question: Because we ran setup.py so it gets stored in your default libraries just like anything downloaded via Pip would.

________________________________

**Comment by adamhyman** [comment]
When this code runs, it doesn't find Krakenex.  Because the Krakenex module is within the python-krakenex folder.

![image](https://user-images.githubusercontent.com/1277113/27699254-812fe8d6-5cae-11e7-9722-4cbf5822af36.png)

This is the error message:

`Python 3.6.2rc1 (heads/3.6:268e1fb, Jun 17 2017, 19:01:44) [MSC v.1900 64 bit (AMD64)] on win32`
`Type "copyright", "credits" or "license()" for more information.`
`>>> `
`====== RESTART: C:\Users\ahyman\Dropbox\Crypto\dinar\exchange_query.py ======`
`Traceback (most recent call last):`
`  File "C:\Users\ahyman\Dropbox\Crypto\dinar\exchange_query.py", line 3, in <module>`
`    from exchange_session import exchange_session`
`  File "C:\Users\ahyman\Dropbox\Crypto\dinar\exchange_session.py", line 5, in <module>`
`    import krakenex`
`ModuleNotFoundError: No module named 'krakenex'`
`>>> `

**Comment by bustoutfunk** [comment]
Did you run setup.py? in the kraken folder?

**Comment by adamhyman** [comment]
AWESOME.  I see.

I have to run python3-krakenex\Setup.py first, then I can run Exchange_Query!

Now it's working perfectly.  And I can add some other exchanges :)

![image](https://user-images.githubusercontent.com/1277113/27704680-3c2f45a8-5cc0-11e7-8f85-ca0d382b03f6.png)

**Comment by bustoutfunk** [comment]
Awesome. I still need to work on that class. It's not totally modular yet. I'll keep you posted.

________________________________

**Comment by adamhyman** [comment]
I fixed it by replacing:
`import krakenex`

with:
`import importlib`
`krakenex = importlib.import_module("python3-krakenex.krakenex")`

Now you don't need to run `setup.py`

**Comment by bustoutfunk** [comment]
Closing as the bulk of this work has been completed.
